import React from 'react'

const Home = () => {
    return (
        <div>
            <h1 className='text-center'>WELCOME TO HOME</h1>
            <h5>Tata Consultancy Services (TCS) is an Indian multinational IT outsourcing company and subsidiary of Tata Group.
                With more than 600,000 employees across 150 locations and 46 countries,
                TCS is the second largest company in India by market capitalization and eighth by revenue.</h5>
            <p>Tata Consultancy Services (TCS) is an Indian multinational information technology (IT) services and consulting company with its headquarters in Mumbai, Maharashtra.[6][7] It is a part of the Tata Group and operates in 150 locations across 46 countries.[8] In July 2022, it was reported that TCS had over 600,000 employees worldwide.[9] TCS is the second largest Indian company by market capitalization and is among the most valuable IT service brands worldwide, and is the top Big Tech (India) company.[10][11][12] In 2015, TCS was ranked 64th overall in the Forbes "World's Most Innovative Companies" ranking, making it one of the highest-ranked IT services companies and a top Indian company.[13] As on Jun 2023, it is the world's 2nd largest IT employer.[14]

                As of 2018, it is ranked eleventh on the Fortune India 500 list.[15] In September 2021,
                TCS recorded a market capitalization of US$200 billion, making it the first Indian IT tech company to do so.
                [16][17][18] In December 2022, the market cap was Rs. 11,71,481.89 crore.
                [19] In 2016–2017, parent company Tata Sons owned 72.05% of TCS[20] and more than 70% of Tata Sons' dividends were generated by TCS</p>


        </div>
    )
}
export default Home;